export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CLEAR_VALIDATION_ERRORS = 'CLEAR_VALIDATION_ERRORS';
export const TOGGLE_ADMIN_PANEL = 'TOGGLE_ADMIN_PANEL';
export const AUTOLOGIN = 'AUTOLOGIN';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
